// Generated by scripts/export-abis.mjs from contracts/deployments. Do not edit.
export const generatedDeployments = {
  "31337": {
    "agentRegistry": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
    "block": 0,
    "chainId": 31337,
    "deployer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "epochManager": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
    "feeManager": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
    "marketCalendar": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "optionToken": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    "pricer": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "stockOracle": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "stocks": {
      "NVDA": {
        "feed": "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f",
        "token": "0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44"
      },
      "TSLA": {
        "feed": "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
        "token": "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"
      }
    },
    "usdg": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "vaultFactory": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
    "vaultImplementation": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
    "vaults": {
      "TSLA_cash_secured_put": "0xe082b26cEf079a095147F35c9647eC97c2401B83",
      "TSLA_covered_call": "0x8aCd85898458400f7Db866d53FCFF6f0D49741FF",
      "agentId": 1,
      "agentSigner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    }
  },
  "46630": {
    "agentRegistry": "0xAa3CA7847Af10d94CCD3eF09370Aab580A92341E",
    "block": 125866639,
    "chainId": 46630,
    "deployer": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
    "epochManager": "0xB8Ed17588AB022d8f84b8305d784Fa01478Cb7F0",
    "feeManager": "0xaD2C4aC0db613F2c7e3F060Bfdd1276912154569",
    "marketCalendar": "0xefD1121ef13F1187F9ac9A54076DFa09A586d31D",
    "optionToken": "0x63614FB8594F0C24CfB8F419326eB3BA7C3274A7",
    "pricer": "0x79A4158900579FA0eE5b413B4724D010C8a0A8E2",
    "stockOracle": "0x8B89A4dE3d8E74888e0135CCBeE5eE00Df36bA9F",
    "stocks": {
      "AMD": {
        "feed": "0x726a9c2a36Eb8511CB067A4FB06B49efB279eE1b",
        "token": "0x71178BAc73cBeb415514eB542a8995b82669778d"
      },
      "AMZN": {
        "feed": "0x1bE23389861F38FAdf8120134b967f7a991Daa82",
        "token": "0x5884aD2f920c162CFBbACc88C9C51AA75eC09E02"
      },
      "NFLX": {
        "feed": "0xaA6D2cfE7ad546499dddedFb0c96F88bA75439A5",
        "token": "0x3b8262A63d25f0477c4DDE23F83cfe22Cb768C93"
      },
      "PLTR": {
        "feed": "0x7C6A9F05D52d8D10624522973258B28D87756Ff9",
        "token": "0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0"
      },
      "TSLA": {
        "feed": "0x8401bcb990005fCEB1390C0b10dA5bE283d6cC0F",
        "token": "0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E"
      }
    },
    "usdg": "0x7E955252E15c84f5768B83c41a71F9eba181802F",
    "vaultFactory": "0x9DbaFfD488FC591947149E2b27189A201C0a74f4",
    "vaultImplementation": "0x5Fe632C9F6Df4ECb11dfef5a6112154379BCd197",
    "stylusPricer": "0x60e947b8d2c2c34b95d88d02f0a06aefb6ccd04c",
    "vaults": {
      "TSLA_cash_secured_put": "0x02B701210aA006CEAbd389dBc32af0047B1B9bbe",
      "TSLA_covered_call": "0x5655659E18bf54ee0EF8f6A816E2e18D000F7311",
      "agentId": 1,
      "agentSigner": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff"
    }
  }
} as const;
