// Generated by scripts/export-abis.mjs from contracts/deployments. Do not edit.
export const generatedDeployments = {
  "31337": {
    "agentRegistry": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
    "block": 0,
    "chainId": 31337,
    "deployer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "epochManager": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
    "feeManager": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
    "marketCalendar": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "optionToken": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    "pricer": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "stockOracle": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "stocks": {
      "NVDA": {
        "feed": "0x4A679253410272dd5232B3Ff7cF5dbB88f295319",
        "token": "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"
      },
      "TSLA": {
        "feed": "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
        "token": "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"
      }
    },
    "usdg": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "vaultFactory": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
    "vaultImplementation": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
    "vaults": {
      "TSLA_cash_secured_put": "0xe082b26cEf079a095147F35c9647eC97c2401B83",
      "TSLA_covered_call": "0x8aCd85898458400f7Db866d53FCFF6f0D49741FF",
      "agentId": 1,
      "agentSigner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    }
  },
  "46630": {
    "agentRegistry": "0xE5b76249041e59C74Ee317fC2729f26249618D32",
    "block": 125880607,
    "chainId": 46630,
    "deployer": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
    "epochManager": "0x5A3b58DF27e4DD5E0fa6493D90fF653e0E199C99",
    "feeManager": "0x6b23819bC44EEbE1BD004208c0F00f2ed002B621",
    "marketCalendar": "0x214d21F4fCA2226091AF009B9F1BF1D3C63f95F4",
    "optionToken": "0x557060266F4aE09ae723541AC8E7E27A99B0c9DB",
    "pricer": "0x4261d47E6487e2533EdB9D5F91242F28121d5A1A",
    "stockOracle": "0x7bb3cAb211E7Ce51e37693E0155C77f477F8aB89",
    "stocks": {
      "AMD": {
        "feed": "0xf7f60670f8D45a648b2844aF1d25c2C6C02ffA4E",
        "token": "0x71178BAc73cBeb415514eB542a8995b82669778d"
      },
      "AMZN": {
        "feed": "0x698a624940DdAfA8380dbF933AbC1c2908796877",
        "token": "0x5884aD2f920c162CFBbACc88C9C51AA75eC09E02"
      },
      "NFLX": {
        "feed": "0xc7e34AC0E39663b580Fe044c04F2b7aa7949b30D",
        "token": "0x3b8262A63d25f0477c4DDE23F83cfe22Cb768C93"
      },
      "PLTR": {
        "feed": "0x2992a2661f4eb802EFF63a985914a80D262c5291",
        "token": "0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0"
      },
      "TSLA": {
        "feed": "0x5476cb08769f406dE95F6171AcC1F5FE88431230",
        "token": "0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E"
      }
    },
    "usdg": "0x7E955252E15c84f5768B83c41a71F9eba181802F",
    "vaultFactory": "0x5665E02878fA592513C1633af2F07b08cF606beC",
    "vaultImplementation": "0x900e7C78598C3AbC38FDD411756c38CF7931797D",
    "stylusPricer": "0x60e947b8d2c2c34b95d88d02f0a06aefb6ccd04c",
    "version": "v2",
    "status": "current",
    "sourceCommit": "1ff5382",
    "deployCommit": "beb4281",
    "activePricer": "0x60e947b8d2c2c34b95d88d02f0a06aefb6ccd04c",
    "activePricerNote": "EpochManager.pricer() is the Stylus pricer; `pricer` is the Solidity reference kept for the on-chain equality check",
    "decisionLog": "0xbF94f54fd0258ac59e2f54B70754dFAfFd245D93",
    "decisionLogTx": "0x9b2e902c16ef74f8f1180ecc5514cbcda3c1c5076a086e3a60e2da06a568665d",
    "decisionLogNote": "Additive (not part of v2): anchors agents' decision records; only AgentRegistry.signerOf(agentId) may record",
    "riskEngine": "0x61158d98c6c2b7ccb22755a098d0da2bbcf2a4ec",
    "riskEngineNote": "Additive (v3's Stylus pricer and risk engine, IRiskEngine; deployed with v3 in 46630-v3.json on branch v3-contracts, verified with cargo stylus verify). Pure math, no state: the SDK's seriesRisk, the MCP tool series_risk and the app's Risk panel call it on v2 series",
    "vaults": {
      "TSLA_cash_secured_put": "0xE33EAD75Df1aF35cBA330f1fc7636926e31c67d7",
      "TSLA_covered_call": "0xADFF7900dbe01E8170a750AB88e1f4eA8D9D1D4e",
      "agentId": 1,
      "agentSigner": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff"
    }
  }
} as const;
