// Generated by scripts/export-abis.mjs from contracts/deployments. Do not edit.
export const generatedDeployments = {
  "31337": {
    "agentRegistry": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
    "block": 0,
    "chainId": 31337,
    "deployer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "epochManager": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
    "feeManager": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
    "marketCalendar": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "optionToken": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    "pricer": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "stockOracle": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "stocks": {
      "NVDA": {
        "feed": "0x4A679253410272dd5232B3Ff7cF5dbB88f295319",
        "token": "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"
      },
      "TSLA": {
        "feed": "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
        "token": "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"
      }
    },
    "usdg": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "usdgDrip": "0x95401dc811bb5740090279Ba06cfA8fcF6113778",
    "vaultFactory": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
    "vaultImplementation": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
    "vaults": {
      "TSLA_cash_secured_put": "0xe082b26cEf079a095147F35c9647eC97c2401B83",
      "TSLA_covered_call": "0x8aCd85898458400f7Db866d53FCFF6f0D49741FF",
      "agentId": 1,
      "agentSigner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    }
  },
  "46630": {
    "agentRegistry": "0xE5b76249041e59C74Ee317fC2729f26249618D32",
    "block": 125880607,
    "chainId": 46630,
    "deployer": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
    "epochManager": "0x5A3b58DF27e4DD5E0fa6493D90fF653e0E199C99",
    "feeManager": "0x6b23819bC44EEbE1BD004208c0F00f2ed002B621",
    "marketCalendar": "0x214d21F4fCA2226091AF009B9F1BF1D3C63f95F4",
    "optionToken": "0x557060266F4aE09ae723541AC8E7E27A99B0c9DB",
    "pricer": "0x4261d47E6487e2533EdB9D5F91242F28121d5A1A",
    "stockOracle": "0x7bb3cAb211E7Ce51e37693E0155C77f477F8aB89",
    "stocks": {
      "AMD": {
        "feed": "0xf7f60670f8D45a648b2844aF1d25c2C6C02ffA4E",
        "token": "0x71178BAc73cBeb415514eB542a8995b82669778d"
      },
      "AMZN": {
        "feed": "0x698a624940DdAfA8380dbF933AbC1c2908796877",
        "token": "0x5884aD2f920c162CFBbACc88C9C51AA75eC09E02"
      },
      "NFLX": {
        "feed": "0xc7e34AC0E39663b580Fe044c04F2b7aa7949b30D",
        "token": "0x3b8262A63d25f0477c4DDE23F83cfe22Cb768C93"
      },
      "PLTR": {
        "feed": "0x2992a2661f4eb802EFF63a985914a80D262c5291",
        "token": "0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0"
      },
      "TSLA": {
        "feed": "0x5476cb08769f406dE95F6171AcC1F5FE88431230",
        "token": "0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E"
      }
    },
    "usdg": "0x7E955252E15c84f5768B83c41a71F9eba181802F",
    "vaultFactory": "0x5665E02878fA592513C1633af2F07b08cF606beC",
    "vaultImplementation": "0x900e7C78598C3AbC38FDD411756c38CF7931797D",
    "stylusPricer": "0x60e947b8d2c2c34b95d88d02f0a06aefb6ccd04c",
    "version": "v2",
    "status": "current",
    "sourceCommit": "1ff5382",
    "deployCommit": "beb4281",
    "activePricer": "0x60e947b8d2c2c34b95d88d02f0a06aefb6ccd04c",
    "activePricerNote": "EpochManager.pricer() is the Stylus pricer; `pricer` is the Solidity reference kept for the on-chain equality check",
    "decisionLog": "0xbF94f54fd0258ac59e2f54B70754dFAfFd245D93",
    "decisionLogTx": "0x9b2e902c16ef74f8f1180ecc5514cbcda3c1c5076a086e3a60e2da06a568665d",
    "decisionLogNote": "Additive (not part of v2): anchors agents' decision records; only AgentRegistry.signerOf(agentId) may record",
    "riskEngine": "0x61158d98c6c2b7ccb22755a098d0da2bbcf2a4ec",
    "riskEngineNote": "Additive (v3's Stylus pricer and risk engine, IRiskEngine; deployed with v3 in 46630-v3.json on branch v3-contracts, verified with cargo stylus verify). Pure math, no state: the SDK's seriesRisk, the MCP tool series_risk and the app's Risk panel call it on v2 series",
    "usdgDrip": "0x1f3778BfC474419f154AD543625A711d90985632",
    "usdgDripTx": "0x705290d78e669cd46db507a08154680aaa7d95e9ba06df2bdb6843ca9c02965b",
    "usdgDripFundTx": "0x4a238e8a69c630f94df50fcea07d062519acc90d6f81a04dd60f32a3f7027629",
    "usdgDripNote": "Additive (testnet only, not part of v2): the team-funded test-USDG faucet, 10 USDG per address per 24 h (UsdgDrip, D38); serves v2 and v3, which use the same USDG",
    "gasDrip": "0x8dC1296314Df514e4fC86720DD26f0b4F3D10b27",
    "gasDripTx": "0x951279ff1a89a37af55a03380363ac28c0ad3e7119e6407bb1687738c134623f",
    "gasDripFundTx": "0xd284e812e9aabd6d90805fc792524a0996eac332d8840a2655f8795421422219",
    "gasDripRelayer": "0xA84936fA307909e01C3C9710D4cEE179385d5e9c",
    "gasDripRelayerFundTx": "0x911a93dbece25b91d65d490fa2e69108223f482f95167e1792c910f5ac3e82c6",
    "gasDripNote": "Additive (testnet only): the team-funded starter gas drip, 0.0001 ETH once per address to wallets holding less than that, at most 20 per UTC day, sent by the /api/gas-drip relayer (GasDrip, D47). Deployed in block 128,261,147; serves every Strike deployment on this chain",
    "vaults": {
      "TSLA_cash_secured_put": "0xE33EAD75Df1aF35cBA330f1fc7636926e31c67d7",
      "TSLA_covered_call": "0xADFF7900dbe01E8170a750AB88e1f4eA8D9D1D4e",
      "agentId": 1,
      "agentSigner": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff"
    }
  },
  "421614": {
    "agentRegistry": "0xAa3CA7847Af10d94CCD3eF09370Aab580A92341E",
    "block": 314350623,
    "chainId": 421614,
    "deployer": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
    "epochManager": "0xB8Ed17588AB022d8f84b8305d784Fa01478Cb7F0",
    "feeManager": "0xaD2C4aC0db613F2c7e3F060Bfdd1276912154569",
    "marketCalendar": "0xefD1121ef13F1187F9ac9A54076DFa09A586d31D",
    "optionToken": "0x63614FB8594F0C24CfB8F419326eB3BA7C3274A7",
    "pricer": "0x79A4158900579FA0eE5b413B4724D010C8a0A8E2",
    "riskLens": "0x94aC10fF1A71ceBfD825079aaf897858a9953ecE",
    "stockOracle": "0x8B89A4dE3d8E74888e0135CCBeE5eE00Df36bA9F",
    "stocks": {
      "NVDA": {
        "feed": "0x1B137e5CB2c0153B4B3f1cbBC78DdECBa5569aA1",
        "token": "0xdF0f069EfF103655312E15C517324d316fD34bc1"
      },
      "TSLA": {
        "feed": "0x85B92cF975E3cf9Ad44c0664d6aF67f358360FFA",
        "token": "0x2EbdbAe172d733f96F9742A7e319e311E552BF37"
      }
    },
    "usdg": "0xFFC95faa3d63Cde504a05B567C600B78C0b41892",
    "vaultFactory": "0x9DbaFfD488FC591947149E2b27189A201C0a74f4",
    "vaultImplementation": "0x5Fe632C9F6Df4ECb11dfef5a6112154379BCd197",
    "l1Block": 11815871,
    "deployTxRange": "L2 blocks 314350623-314351025",
    "blockNote": "block is the Arbitrum Sepolia (L2) deployment block, where event scans start; Deploy.s.sol wrote block.number, which on Arbitrum is the L1 (Sepolia) block, kept as l1Block",
    "version": "v3",
    "network": "Arbitrum Sepolia",
    "decisionLog": "0x60E947b8d2c2C34b95d88d02F0A06AeFb6Ccd04C",
    "decisionLogTx": "0x8cea8ec3097530fbf188719e6775946bf4d88bf6a19bad73726832316462e8c1",
    "decisionLogNote": "Additive, reads this AgentRegistry; source contracts/src/agents/DecisionLog.sol on main (9ed81b4)",
    "testnetNote": "Real Sepolia USDG (Paxos). TSLA and NVDA are TestStockTokens with a faucet (10 per address per day); their MirrorFeeds copy the Robinhood Chain mainnet Chainlink rounds (seeded with the mainnet round current at deploy time)",
    "agent": {
      "agentId": 1,
      "owner": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
      "signer": "0x4fd9565bf8C0Bda9bBdF2Add233d19c64e50AC6f",
      "erc8004Id": 253,
      "registerTx": "0xb1d1d505b5312d63e2f044b73838412774674d9e2e90d29a51217ad24897a5ae",
      "postBondTx": "0x81fcc53457ed9d6ac539783b37b0f157606f4a65d1bef7bcc90e5f030a0fe03d",
      "erc8004RegisterTx": "0x2f99add127c63313b1277df97680387dcf4e1f26e0487618e826a12df6b4d435",
      "setIdentityTx": "0x62b8c7bb68b0ff6f18227a95f0f51e619dd28f365250d7e43c67f867bf2960b8",
      "note": "Registered by the owner with the signer's EIP-712 Register consent (Seed.s.sol, BOND=60e6); ERC-8004 identity #253 on the official Identity Registry 0x8004A818...BD9e on Arbitrum Sepolia",
      "bond": "60 USDG posted, 50 after the 10 USDG slash on 2026-09-30"
    },
    "stylusPricer": "0x57cfa61b190c1e80d6e8b1549b8acf1bc505a531",
    "stylusPricerTx": "0x7ffbd7b93393569dced980712220ed02ec6c62a66b1c8a0ae3bc5cf690dad3c8",
    "stylusActivationTx": "0xa68de6166937fc3c22d3cbe30fe2e3d5efda93ffe57e4570b1bf495bf136a287",
    "activePricer": "0x57cfa61b190c1e80d6e8b1549b8acf1bc505a531",
    "activePricerNote": "EpochManager.pricer() is the Stylus pricer and risk engine (setPricer tx 0x132d5bb34afb19ba5a18316250644091c83a051518aca5ece7a3681b3ba82f59) after the on-chain equality check; `pricer` is the Solidity reference (BlackScholesRef with RiskLib)",
    "riskEngine": "0x57cfa61b190c1e80d6e8b1549b8acf1bc505a531",
    "sourceCommit": "ebe139e",
    "deployCommit": "e705aaf",
    "status": "deployed; live epoch 2026-09-30 (series expires 2026-10-02 20:00 UTC)",
    "stylusCache": {
      "bidTx": "0x5b1d2385b65c8a9487cb544ac9a187796a7af920950e50e80461fb7857cf596f",
      "bidWei": 0,
      "note": "Cached in ArbOS via the CacheManager; saves about 19,800 gas per call into the program"
    },
    "epoch1": {
      "callVaultSeries": "8200340887102394470889505950118944065123972136398888610989328404594772867353",
      "strike": "364.29",
      "expiry": 1790971200,
      "openEpochTx": "0x9865efd793e63ee8386e4a670eeb0bc65f5d45f1c3070126bc295f261a98de59",
      "proposeByDeltaTx": "0xf26315b33df93548bfa31d68b7d9964792ef88184cb154796180e19b9365b5f4",
      "rejectedPutTx": "0x4813b1089c8e6a3f3e728c74b9b6bb2d79ec73fb36ab0b5142abc72aa333756d",
      "buyTx": "0x82e2d5b4e476edec205c80daca431a8becdd5fbdb1f84e3ca0dea8d7d49265f4",
      "decisionLogRecordTxs": [
        "0x1f9f7eafdf448c205df43e81d75e94f5282dd3b2bb465473330012c04cac3538",
        "0x6ee65ef8a6fa002f4388f7cf279f6fd098c0a45ab2bff118c0fc0ab0ed266c8e"
      ]
    },
    "gasDrip": "0x4fF10F0A6C1a9cC9c0a83ceC6c0C5e3dd2293EAd",
    "gasDripTx": "0x27ce6d484a9da04aa6e7b6a09f680d81b58df2420908cd68a7e85096ba0d98ec",
    "gasDripFundTx": "0x2994afe2df148715de0b92c9a4f659f54765d63a05cffe380c5a566c77039b0e",
    "gasDripRelayer": "0xA84936fA307909e01C3C9710D4cEE179385d5e9c",
    "gasDripRelayerFundTx": "0xe67614270edd829a1fb6f4d698aa79ccf60b663a52552927650e9e2ef113887f",
    "gasDripNote": "Additive (testnet only): the team-funded starter gas drip, 0.0001 ETH once per address to wallets holding less than that, at most 20 per UTC day, sent by the /api/gas-drip relayer (GasDrip, D47). Deployed in block 315,393,690; serves every Strike deployment on this chain",
    "vaults": {
      "TSLA_cash_secured_put": "0x02B701210aA006CEAbd389dBc32af0047B1B9bbe",
      "TSLA_covered_call": "0x5655659E18bf54ee0EF8f6A816E2e18D000F7311",
      "agentId": 1,
      "agentSigner": "0x4fd9565bf8C0Bda9bBdF2Add233d19c64e50AC6f"
    }
  }
} as const;

/** Newer deployments next to a chain's primary one (<chainId>-v<N>.json), oldest first. */
export const generatedSecondaryDeployments = {
  "46630": [
    {
      "agentRegistry": "0x1c42740145B245b2f894d8e989ca29dfd9A9052f",
      "block": 126713718,
      "chainId": 46630,
      "deployer": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
      "epochManager": "0x256D4546486368dCb23E94758b4cb500c215929F",
      "feeManager": "0x8DBE22eAa3CEFC367C435ce2b6F779fabe7D2Fa7",
      "marketCalendar": "0x214d21F4fCA2226091AF009B9F1BF1D3C63f95F4",
      "optionToken": "0xfbeb6cf8350C182c7895165A8Fdd3D9884aB46B6",
      "pricer": "0x2B6A2A51bd802Ed11bE7c0B954a7Ec9287c362d0",
      "riskLens": "0xFDb8Ba33f4aAF1A699f1D5877E8ee5b6eDeDCc6D",
      "stockOracle": "0x5BCdBFaB940BFAEF821392d7f58c670c2064989A",
      "stocks": {
        "AMD": {
          "feed": "0xf7f60670f8D45a648b2844aF1d25c2C6C02ffA4E",
          "token": "0x71178BAc73cBeb415514eB542a8995b82669778d"
        },
        "AMZN": {
          "feed": "0x698a624940DdAfA8380dbF933AbC1c2908796877",
          "token": "0x5884aD2f920c162CFBbACc88C9C51AA75eC09E02"
        },
        "NFLX": {
          "feed": "0xc7e34AC0E39663b580Fe044c04F2b7aa7949b30D",
          "token": "0x3b8262A63d25f0477c4DDE23F83cfe22Cb768C93"
        },
        "PLTR": {
          "feed": "0x2992a2661f4eb802EFF63a985914a80D262c5291",
          "token": "0x1FBE1a0e43594b3455993B5dE5Fd0A7A266298d0"
        },
        "TSLA": {
          "feed": "0x5476cb08769f406dE95F6171AcC1F5FE88431230",
          "token": "0xC9f9c86933092BbbfFF3CCb4b105A4A94bf3Bd4E"
        }
      },
      "usdg": "0x7E955252E15c84f5768B83c41a71F9eba181802F",
      "vaultFactory": "0x97ab9ed707758Fc23b4e59132d97Ab7cb9fb215e",
      "vaultImplementation": "0x2E67F1Cf23eAAeecaee36d248d76e8366DA076D9",
      "stylusPricer": "0x61158d98c6c2b7ccb22755a098d0da2bbcf2a4ec",
      "stylusPricerTx": "0xc71be99442c8bbc9b9be9d419795ac2709b95b8b70214a465a71aeef9b89d49a",
      "stylusActivationTx": "0x19277b827e7b979963e71118f69874b83c3d6c69acac58a494c49881efed417a",
      "version": "v3",
      "status": "deployed next to v2, not yet the app default; live epoch 2026-10-01 (series expires 2026-10-02 20:00 UTC)",
      "sourceCommit": "448d83b",
      "deployCommit": "64fcb93",
      "activePricer": "0x61158d98c6c2b7ccb22755a098d0da2bbcf2a4ec",
      "activePricerNote": "EpochManager.pricer() is the Stylus pricer and risk engine (setPricer tx 0x086c2ec2d3eec2d4c389c6890bea06a2df7a1aa5140eecf9e3e27a0da100f309); `pricer` is the Solidity reference (BlackScholesRef with RiskLib), kept for the on-chain equality check",
      "sharedWithV2": "marketCalendar and the five stock MirrorFeeds are v2's (same source), so one keeper fills both versions",
      "decisionLog": "0xa98106db53519F8cfE4D7C56B34D4Fe0460403a4",
      "decisionLogTx": "0xf55e1d4dfe09759377b3da3e9feab6a39727ff0bc71251b2fd6ec3148f896c28",
      "decisionLogNote": "Additive, reads this v3 AgentRegistry; source contracts/src/agents/DecisionLog.sol on main (a98fff8). v2's DecisionLog reads the v2 registry and cannot authorise v3 signers",
      "agent": {
        "agentId": 1,
        "owner": "0x26b277b434B1670f207Afd8946edA9AF78A613Ff",
        "signer": "0x4fd9565bf8C0Bda9bBdF2Add233d19c64e50AC6f",
        "erc8004Id": 114,
        "registerTx": "0x52f5999da7ab48d37ffb8fc5d3b476b9da1c0d3faa855de645cb80a784827162",
        "setIdentityTx": "0xc617c3eb7feb026513bf791bb0e1c2108d4821bd86995c49a14f391832904154",
        "note": "Registered by the owner with the signer's EIP-712 Register consent (domain Strike AgentRegistry / 1). Bonded 2026-10-01 by the signer itself (60 USDG)",
        "postBondTx": "0x23a42953480fe13db45b0ebbfba10f7d44d06052a52192ed78989c5ae6517581",
        "bondApproveTx": "0x0eb488c20fb5ca49d1070163c32455d09425be29c99816ae9a98da3bf3b68fd4",
        "bond": "60 USDG posted, 50 after the 10 USDG slash on 2026-10-01"
      },
      "vaults": {
        "TSLA_cash_secured_put": "0x1bc73c1B28F520E57982FAe6127477190FA53690",
        "TSLA_covered_call": "0x478E7BC3C3aB07fdd104e4765F178977adEe6285",
        "agentId": 1,
        "agentSigner": "0x4fd9565bf8C0Bda9bBdF2Add233d19c64e50AC6f"
      },
      "epoch1": {
        "callVaultSeries": "48103703716925406245656156603615117052914973735876202170787552644395932337728",
        "strike": "369.36",
        "expiry": 1790971200,
        "openEpochTx": "0x4b179fb1809a4777961e5fe1439f7ad4dd2c418f4cc2e20c99b397d561d959e1",
        "proposeByDeltaTx": "0xe823a351b82404077c126482ca61f6be9c1c461606b4626f55bea1898d335a45",
        "putOpenEpochTx": "0x6feeaeebac01b2288ea6000557b4c9d4f41bfecd73c25808dc2fc0a2e4239fc3",
        "rejectedPutTx": "0xa8b5eba59bbffd9203c9deab6053754df82f69396fbc03b41de2a9897de7efb2",
        "buyTx": "0x16d9345d815d1d5fb5a39540533b725367cfbaeab0287647f984d0202b6a61fc",
        "decisionLogRecordTxs": [
          "0x00e27fe12ab6b01507f55aba3b32b9576d2bcdf84dbede88c8bee2223aef6388",
          "0x966985d8ca2026bb6426a46d35ae708a48724a6ed74208a1ecd9c65fbf4a6e27"
        ]
      }
    }
  ]
} as const;
