// The committed backtest (research/backtest.py → research/results/*), as the /app/backtest page reads it.
// The JSON under src/data/backtest is generated by `node app/scripts/backtest-data.mjs`; nothing here recomputes a
// published metric. The page only derives what the CSVs imply directly: histogram counts and period labels.

import summaryJson from "@/data/backtest/summary.json";
import weeklyJson from "@/data/backtest/weekly.json";

export const TICKERS = ["TSLA", "NVDA", "AMZN", "SPY"] as const;
export type Ticker = (typeof TICKERS)[number];
export type Vault = "call" | "put";
export type Vrp = "1.00" | "1.15";
export const VAULTS: Vault[] = ["call", "put"];
export const VRPS: Vrp[] = ["1.00", "1.15"];

export const VAULT_NAME: Record<Vault, string> = { call: "Covered call", put: "Cash-secured put" };

export interface GridRow {
  ticker: Ticker;
  vault: Vault;
  delta: number;
  vrp: Vrp;
  weeks: number;
  cagr: number;
  vol: number;
  sharpe: number;
  maxDd: number;
  worstWeek: number;
  assigned: number;
  /** Premium per option ÷ collateral per option, mean over the weeks (a fraction). */
  avgPremium: number;
  bhCagr: number;
  bhVol: number;
  bhSharpe: number;
  bhMaxDd: number;
  bhWorstWeek: number;
}

export interface StressRow {
  ticker: Ticker;
  vault: Vault;
  vrp: Vrp;
  /** [vault %, buy-and-hold %], as tables.md prints them. */
  crash: [number, number];
  rebound: [number, number];
  bear: [number, number];
}

export interface Period {
  label: string;
  from: string;
  to: string;
}

/** As stored: comma-joined numbers (see app/scripts/backtest-data.mjs). */
interface VaultSeries {
  nav: string;
  premium: string;
  itm: string;
}

interface Summary {
  meta: { weeks: number; start: string; end: string; premiumBps: number; premiumHeld: boolean };
  periods: Period[];
  grid: GridRow[];
  stress: StressRow[];
}

interface Weekly {
  delta: number;
  dates: string;
  series: Record<Ticker, { bh: string } & Record<Vault, Record<Vrp, VaultSeries>>>;
}

const nums = (s: string) => s.split(",").map(Number);

const summary = summaryJson as unknown as Summary;
const weekly = weeklyJson as unknown as Weekly;

export const META = summary.meta;
export const PERIODS = summary.periods;
/** Delta of the week-by-week series (the grid alone covers the others). */
export const SERIES_DELTA = weekly.delta;
/** The first open, then each weekly settlement date. */
const DATES = weekly.dates.split(",");
export const DELTAS = [...new Set(summary.grid.map((g) => g.delta))].sort((a, b) => a - b);

export interface Selection {
  ticker: Ticker;
  vault: Vault;
  vrp: Vrp;
}

export function gridRow(sel: Selection, delta = SERIES_DELTA): GridRow {
  const row = summary.grid.find(
    (g) => g.ticker === sel.ticker && g.vault === sel.vault && g.vrp === sel.vrp && g.delta === delta,
  );
  if (!row) throw new Error(`no grid row for ${sel.ticker} ${sel.vault} ${sel.vrp} ${delta}`);
  return row;
}

export function deltaRows(sel: Selection): GridRow[] {
  return DELTAS.map((d) => gridRow(sel, d));
}

export function stressRow(sel: Selection): StressRow {
  const row = summary.stress.find(
    (s) => s.ticker === sel.ticker && s.vault === sel.vault && s.vrp === sel.vrp,
  );
  if (!row) throw new Error(`no stress row for ${sel.ticker} ${sel.vault} ${sel.vrp}`);
  return row;
}

export interface EquityPoint {
  date: string;
  /** Epoch ms, for the time axis. */
  t: number;
  vault: number;
  bh: number;
  /** Did the week ending here finish in the money? (null for the starting point) */
  assigned: boolean | null;
}

export function equitySeries(sel: Selection): EquityPoint[] {
  const s = weekly.series[sel.ticker];
  const v = s[sel.vault][sel.vrp];
  const nav = nums(v.nav);
  const bh = nums(s.bh);
  return DATES.map((date, i) => ({
    date,
    t: Date.parse(`${date}T00:00:00Z`),
    vault: nav[i],
    bh: bh[i],
    assigned: i === 0 ? null : v.itm[i - 1] === "1",
  }));
}

/** Weekly premium per option as % of collateral, one value per week. */
export function premiumSeries(sel: Selection): number[] {
  return nums(weekly.series[sel.ticker][sel.vault][sel.vrp].premium);
}

export interface Bin {
  /** In % of collateral. */
  lo: number;
  hi: number;
  count: number;
}

/** Equal-width bins on a clean step, from 0 to past the largest week. */
export function histogram(values: number[], target = 18): Bin[] {
  const max = Math.max(...values);
  const step = niceStep(max, target);
  const n = Math.max(1, Math.ceil((max + 1e-12) / step));
  const bins: Bin[] = Array.from({ length: n }, (_, i) => ({
    lo: round(i * step),
    hi: round((i + 1) * step),
    count: 0,
  }));
  for (const v of values) bins[Math.min(n - 1, Math.floor(v / step))].count++;
  return bins;
}

// ------------------------------------------------------------------ scales & formatting

const round = (n: number) => Number(n.toFixed(10));

export function niceStep(span: number, target: number): number {
  const raw = span / Math.max(1, target);
  const pow = 10 ** Math.floor(Math.log10(raw));
  const unit = [1, 2, 2.5, 5, 10].find((m) => m * pow >= raw) ?? 10;
  return unit * pow;
}

export function ticks(lo: number, hi: number, target: number): number[] {
  const step = niceStep(hi - lo, target);
  const out: number[] = [];
  for (let v = Math.ceil(lo / step - 1e-9) * step; v <= hi + 1e-9; v += step) out.push(round(v));
  return out;
}

/** Clean ticks for a log axis: 1-2-5 per decade, thinned to about `target`. */
export function logTicks(lo: number, hi: number, target = 6): number[] {
  const all: number[] = [];
  for (let e = Math.floor(Math.log10(lo)); e <= Math.ceil(Math.log10(hi)); e++)
    for (const m of [1, 2, 5]) {
      const v = round(m * 10 ** e);
      if (v >= lo * 0.999 && v <= hi * 1.001) all.push(v);
    }
  if (all.length <= target) return all;
  const ones = all.filter((v) => Math.abs(Math.log10(v) - Math.round(Math.log10(v))) < 1e-9);
  return ones.length >= 2 ? ones : all.filter((_, i) => i % 2 === 0);
}

const MINUS = "−";

/** 0.172 → "17.2%"; signed adds "+" to positives. */
export function pct(fraction: number, frac = 1, signed = false): string {
  return pctOf(fraction * 100, frac, signed);
}

/** 17.2 → "17.2%" (the value is already in percent). */
export function pctOf(percent: number, frac = 1, signed = false): string {
  const r = Number(percent.toFixed(frac));
  const body = `${Math.abs(r).toFixed(frac)}%`;
  if (r < 0) return `${MINUS}${body}`;
  return signed && r > 0 ? `+${body}` : body;
}

export function num(n: number, frac = 2): string {
  const r = Number(n.toFixed(frac));
  return `${r < 0 ? MINUS : ""}${Math.abs(r).toFixed(frac)}`;
}

/** Growth multiple: 3.3981 → "3.40×". */
export function times(n: number): string {
  return `${n >= 10 ? n.toFixed(1) : n.toFixed(2)}×`;
}

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/** "2020-03-20" → "20 Mar 2020". */
export function fmtDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return `${d} ${MONTHS[m - 1]} ${y}`;
}

/** "2020-02-14" → "14 Feb". */
export function fmtDayMonth(iso: string): string {
  const [, m, d] = iso.split("-").map(Number);
  return `${d} ${MONTHS[m - 1]}`;
}

// ------------------------------------------------------------------ sources

export const GH = "https://github.com/Prashant-thakur77/Strike/blob/main";
export const SOURCES = {
  doc: `${GH}/docs/backtest.md`,
  script: `${GH}/research/backtest.py`,
  tables: `${GH}/research/results/tables.md`,
  grid: `${GH}/research/results/grid.csv`,
};
