#!/usr/bin/env node
// Copies contract ABIs from Foundry output into @strike/sdk and builds the deployments map.
// Run after `forge build` (and after each deployment): node scripts/export-abis.mjs
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const out = join(root, "contracts/out");
const abiDir = join(root, "sdk/src/abi");
mkdirSync(abiDir, { recursive: true });

const contracts = [
  "EpochManager",
  "StrikeVault",
  "VaultFactory",
  "AgentRegistry",
  "OptionToken",
  "FeeManager",
  "StockOracle",
  "MarketCalendar",
  "BlackScholesRef",
  "MirrorFeed",
  "TestStockToken",
  "DecisionLog",
  "UsdgDrip",
];

const camel = (name) => name[0].toLowerCase() + name.slice(1);
const exports = [];
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  const file = join(abiDir, `${camel(name)}.ts`);
  writeFileSync(
    file,
    `// Generated by scripts/export-abis.mjs from contracts/out. Do not edit.\nexport const ${camel(name)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  exports.push(`export { ${camel(name)}Abi } from "./${camel(name)}.js";`);
}
// v3 ABIs, from the `v3-contracts` branch (deployed next to v2; main does not build them): the risk engine and RiskLens,
// and v3's AgentRegistry (EIP-712 signer consent on `register` and `setSigner`), exported as `agentRegistryV3Abi` next
// to v2's `agentRegistryAbi`. Regenerate with STRIKE_V3_OUT=<the v3 worktree's forge out dir>; without it the committed
// files are kept. `IRiskEngine` declares no errors, so the pricer's `PricerInputOutOfRange(uint8)` is added to the two
// risk ABIs for viem to decode reverts.
const v3Out = process.env.STRIKE_V3_OUT;
const pricerError = JSON.parse(
  readFileSync(join(out, "BlackScholesRef.sol", "BlackScholesRef.json"), "utf8"),
).abi.filter((x) => x.type === "error" && x.name === "PricerInputOutOfRange");
for (const [name, exportName, pricerErrors] of [
  ["IRiskEngine", "riskEngine", true],
  ["RiskLens", "riskLens", true],
  ["AgentRegistry", "agentRegistryV3", false],
]) {
  const file = join(abiDir, `${exportName}.ts`);
  if (v3Out) {
    let abi = JSON.parse(readFileSync(join(v3Out, `${name}.sol`, `${name}.json`), "utf8")).abi;
    if (pricerErrors && !abi.some((x) => x.type === "error" && x.name === "PricerInputOutOfRange"))
      abi = [...abi, ...pricerError];
    writeFileSync(
      file,
      `// Generated by scripts/export-abis.mjs from the v3-contracts build (${name}). Do not edit.\nexport const ${exportName}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
    );
  } else if (!existsSync(file)) {
    continue;
  }
  exports.push(`export { ${exportName}Abi } from "./${exportName}.js";`);
}
writeFileSync(join(abiDir, "index.ts"), `// Generated. Do not edit.\n${exports.join("\n")}\n`);

// Deployments: contracts/deployments/<chainId>.json and <chainId>-vaults.json
const depDir = join(root, "contracts/deployments");
const deployments = {};
if (existsSync(depDir)) {
  for (const f of readdirSync(depDir)) {
    const m = f.match(/^(\d+)\.json$/);
    if (!m || m[1] === "412346") continue; // local Nitro dev node (gas measurements only)
    const chainId = Number(m[1]);
    const core = JSON.parse(readFileSync(join(depDir, f), "utf8"));
    const vaultsFile = join(depDir, `${chainId}-vaults.json`);
    const vaults = existsSync(vaultsFile) ? JSON.parse(readFileSync(vaultsFile, "utf8")) : {};
    deployments[chainId] = { ...core, vaults };
  }
}
// Secondary deployments: <chainId>-v<N>.json (+ <chainId>-v<N>-vaults.json) of a newer protocol version deployed
// next to a chain's primary one (v3 next to v2 on 46630). The primary stays the chain's default; older versioned
// files (46630-v1.json, superseded) are history and are left out.
const versionNumber = (v) => (typeof v === "string" && /^v\d+$/.test(v) ? Number(v.slice(1)) : null);
const secondary = {};
if (existsSync(depDir)) {
  for (const f of readdirSync(depDir).sort()) {
    const m = f.match(/^(\d+)-(v\d+)\.json$/);
    if (!m || !deployments[m[1]]) continue;
    const primaryVersion = versionNumber(deployments[m[1]].version);
    if (primaryVersion === null || Number(m[2].slice(1)) <= primaryVersion) continue;
    const core = JSON.parse(readFileSync(join(depDir, f), "utf8"));
    const vaultsFile = join(depDir, `${m[1]}-${m[2]}-vaults.json`);
    const vaults = existsSync(vaultsFile) ? JSON.parse(readFileSync(vaultsFile, "utf8")) : {};
    (secondary[m[1]] ??= []).push({ ...core, vaults });
  }
}
writeFileSync(
  join(root, "sdk/src/deployments.generated.ts"),
  `// Generated by scripts/export-abis.mjs from contracts/deployments. Do not edit.\nexport const generatedDeployments = ${JSON.stringify(deployments, null, 2)} as const;\n\n/** Newer deployments next to a chain's primary one (<chainId>-v<N>.json), oldest first. */\nexport const generatedSecondaryDeployments = ${JSON.stringify(secondary, null, 2)} as const;\n`,
);
const nSecondary = Object.values(secondary).reduce((n, l) => n + l.length, 0);
console.log(
  `exported ${contracts.length} ABIs, ${Object.keys(deployments).length} deployment(s) and ${nSecondary} secondary deployment(s)`,
);
