#!/usr/bin/env node
// Copies contract ABIs from Foundry output into @strike/sdk and builds the deployments map.
// Run after `forge build` (and after each deployment): node scripts/export-abis.mjs
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const out = join(root, "contracts/out");
const abiDir = join(root, "sdk/src/abi");
mkdirSync(abiDir, { recursive: true });

const contracts = [
  "EpochManager",
  "StrikeVault",
  "VaultFactory",
  "AgentRegistry",
  "OptionToken",
  "FeeManager",
  "StockOracle",
  "MarketCalendar",
  "BlackScholesRef",
  "MirrorFeed",
  "TestStockToken",
];

const camel = (name) => name[0].toLowerCase() + name.slice(1);
const exports = [];
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  const file = join(abiDir, `${camel(name)}.ts`);
  writeFileSync(
    file,
    `// Generated by scripts/export-abis.mjs from contracts/out. Do not edit.\nexport const ${camel(name)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  exports.push(`export { ${camel(name)}Abi } from "./${camel(name)}.js";`);
}
writeFileSync(join(abiDir, "index.ts"), `// Generated. Do not edit.\n${exports.join("\n")}\n`);

// Deployments: contracts/deployments/<chainId>.json and <chainId>-vaults.json
const depDir = join(root, "contracts/deployments");
const deployments = {};
if (existsSync(depDir)) {
  for (const f of readdirSync(depDir)) {
    const m = f.match(/^(\d+)\.json$/);
    if (!m || m[1] === "412346") continue; // local Nitro dev node (gas measurements only)
    const chainId = Number(m[1]);
    const core = JSON.parse(readFileSync(join(depDir, f), "utf8"));
    const vaultsFile = join(depDir, `${chainId}-vaults.json`);
    const vaults = existsSync(vaultsFile) ? JSON.parse(readFileSync(vaultsFile, "utf8")) : {};
    deployments[chainId] = { ...core, vaults };
  }
}
writeFileSync(
  join(root, "sdk/src/deployments.generated.ts"),
  `// Generated by scripts/export-abis.mjs from contracts/deployments. Do not edit.\nexport const generatedDeployments = ${JSON.stringify(deployments, null, 2)} as const;\n`,
);
console.log(`exported ${contracts.length} ABIs and ${Object.keys(deployments).length} deployment(s)`);
