#!/usr/bin/env node
// Copies contract ABIs from Foundry output into @strike/sdk, bundles strike.config.json into the SDK and builds the
// deployments map from the deployment files the config lists.
// Run after `forge build` (and after each deployment): node scripts/export-abis.mjs
// After changing only strike.config.json or a deployment file (no forge build needed): add --skip-abis.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
if (process.argv.slice(2).includes("--skip-abis")) {
  exportConfigAndDeployments();
  process.exit(0);
}
const out = join(root, "contracts/out");
const abiDir = join(root, "sdk/src/abi");
mkdirSync(abiDir, { recursive: true });

const contracts = [
  "EpochManager",
  "StrikeVault",
  "VaultFactory",
  "AgentRegistry",
  "OptionToken",
  "FeeManager",
  "StockOracle",
  "MarketCalendar",
  "BlackScholesRef",
  "MirrorFeed",
  "TestStockToken",
  "DecisionLog",
  "UsdgDrip",
];

const camel = (name) => name[0].toLowerCase() + name.slice(1);
const exports = [];
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  const file = join(abiDir, `${camel(name)}.ts`);
  writeFileSync(
    file,
    `// Generated by scripts/export-abis.mjs from contracts/out. Do not edit.\nexport const ${camel(name)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  exports.push(`export { ${camel(name)}Abi } from "./${camel(name)}.js";`);
}
// v3 ABIs, from the `v3-contracts` branch (deployed next to v2; main does not build them): the risk engine and RiskLens,
// and v3's AgentRegistry (EIP-712 signer consent on `register` and `setSigner`), exported as `agentRegistryV3Abi` next
// to v2's `agentRegistryAbi`. Regenerate with STRIKE_V3_OUT=<the v3 worktree's forge out dir>; without it the committed
// files are kept. `IRiskEngine` declares no errors, so the pricer's `PricerInputOutOfRange(uint8)` is added to the two
// risk ABIs for viem to decode reverts.
const v3Out = process.env.STRIKE_V3_OUT;
const pricerError = JSON.parse(
  readFileSync(join(out, "BlackScholesRef.sol", "BlackScholesRef.json"), "utf8"),
).abi.filter((x) => x.type === "error" && x.name === "PricerInputOutOfRange");
for (const [name, exportName, pricerErrors] of [
  ["IRiskEngine", "riskEngine", true],
  ["RiskLens", "riskLens", true],
  ["AgentRegistry", "agentRegistryV3", false],
]) {
  const file = join(abiDir, `${exportName}.ts`);
  if (v3Out) {
    let abi = JSON.parse(readFileSync(join(v3Out, `${name}.sol`, `${name}.json`), "utf8")).abi;
    if (pricerErrors && !abi.some((x) => x.type === "error" && x.name === "PricerInputOutOfRange"))
      abi = [...abi, ...pricerError];
    writeFileSync(
      file,
      `// Generated by scripts/export-abis.mjs from the v3-contracts build (${name}). Do not edit.\nexport const ${exportName}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
    );
  } else if (!existsSync(file)) {
    continue;
  }
  exports.push(`export { ${exportName}Abi } from "./${exportName}.js";`);
}
writeFileSync(join(abiDir, "index.ts"), `// Generated. Do not edit.\n${exports.join("\n")}\n`);
console.log(`exported ${contracts.length} ABIs`);

exportConfigAndDeployments();

function exportConfigAndDeployments() {
  // strike.config.json, bundled into the SDK for browsers and the npm package (Node reads the file itself), without
  // the editor-only "$schema" key.
  const config = JSON.parse(readFileSync(join(root, "strike.config.json"), "utf8"));
  delete config.$schema;
  writeFileSync(
    join(root, "sdk/src/config.generated.ts"),
    `// Generated by scripts/export-abis.mjs from strike.config.json. Do not edit.\nimport type { StrikeConfig } from "./config.js";\n\nexport const bundledStrikeConfig: StrikeConfig = ${JSON.stringify(config, null, 2)};\n`,
  );

  // Deployments: each chain's `deployments` list in strike.config.json, the primary first, each with the
  // <file>-vaults.json beside it. The primary is the chain's default; the others (a newer protocol version deployed
  // next to it: 46630-v3.json next to 46630.json) are its secondary deployments, in the listed order. A local
  // devnet's files (31337, `local: true`) exist only after scripts/demo-local.sh and are skipped when absent; a
  // missing file of any other chain is an error.
  const readDeployment = (file) => {
    const core = JSON.parse(readFileSync(join(root, file), "utf8"));
    const vaultsFile = join(root, file.replace(/\.json$/, "-vaults.json"));
    const vaults = existsSync(vaultsFile) ? JSON.parse(readFileSync(vaultsFile, "utf8")) : {};
    return { ...core, vaults };
  };
  const deployments = {};
  const secondary = {};
  for (const [chainId, chain] of Object.entries(config.chains)) {
    const files = chain.deployments.filter((f) => {
      if (existsSync(join(root, f))) return true;
      if (chain.local) return false;
      throw new Error(`strike.config.json lists ${f} for chain ${chainId}, but the file does not exist`);
    });
    if (!files.length) continue;
    deployments[chainId] = readDeployment(files[0]);
    if (files.length > 1) secondary[chainId] = files.slice(1).map(readDeployment);
  }
  writeFileSync(
    join(root, "sdk/src/deployments.generated.ts"),
    `// Generated by scripts/export-abis.mjs from contracts/deployments. Do not edit.\nexport const generatedDeployments = ${JSON.stringify(deployments, null, 2)} as const;\n\n/** Newer deployments next to a chain's primary one (<chainId>-v<N>.json), oldest first. */\nexport const generatedSecondaryDeployments = ${JSON.stringify(secondary, null, 2)} as const;\n`,
  );
  const nSecondary = Object.values(secondary).reduce((n, l) => n + l.length, 0);
  console.log(
    `exported strike.config.json, ${Object.keys(deployments).length} deployment(s) and ${nSecondary} secondary deployment(s)`,
  );
}
