// Generated by scripts/export-abis.mjs from contracts/out. Do not edit.
export const blackScholesRefAbi = [
  {
    "type": "function",
    "name": "delta",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "d",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "price",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "p",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "strikeForDelta",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "targetDelta",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "error",
    "name": "PricerInputOutOfRange",
    "inputs": [
      {
        "name": "which",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  }
] as const;
