// Generated by scripts/export-abis.mjs from the v3-contracts build (IRiskEngine). Do not edit.
export const riskEngineAbi = [
  {
    "type": "function",
    "name": "greeks",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "delta",
        "type": "int256",
        "internalType": "int256"
      },
      {
        "name": "gamma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "vega",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "theta",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "impliedVol",
    "inputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "delta",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scenarioLoss",
    "inputs": [
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sold",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "shocks",
        "type": "int256[]",
        "internalType": "int256[]"
      }
    ],
    "outputs": [
      {
        "name": "worst",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "losses",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "strikeForDelta",
    "inputs": [
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "targetDelta",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timeToExpiry",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "isCall",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "strike",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "PricerInputOutOfRange",
    "inputs": [
      {
        "name": "which",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  }
] as const;
