// Generated by scripts/export-abis.mjs from the v3-contracts build (RiskLens). Do not edit.
export const riskLensAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "manager_",
        "type": "address",
        "internalType": "contract EpochManager"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "defaultShocks",
    "inputs": [],
    "outputs": [
      {
        "name": "shocks",
        "type": "int256[]",
        "internalType": "int256[]"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "manager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract EpochManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "seriesRisk",
    "inputs": [
      {
        "name": "seriesId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct RiskLens.SeriesRisk",
        "components": [
          {
            "name": "spot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sigma",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tenor",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "delta",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "gamma",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vega",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "theta",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "sold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "worstShock",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "worstLoss",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "worstPayout",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "shocks",
            "type": "int256[]",
            "internalType": "int256[]"
          },
          {
            "name": "losses",
            "type": "uint256[]",
            "internalType": "uint256[]"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "seriesRiskAt",
    "inputs": [
      {
        "name": "seriesId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spot",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sigma",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "shocks",
        "type": "int256[]",
        "internalType": "int256[]"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct RiskLens.SeriesRisk",
        "components": [
          {
            "name": "spot",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sigma",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "tenor",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "delta",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "gamma",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vega",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "theta",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "sold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "collateral",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "worstShock",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "worstLoss",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "worstPayout",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "shocks",
            "type": "int256[]",
            "internalType": "int256[]"
          },
          {
            "name": "losses",
            "type": "uint256[]",
            "internalType": "uint256[]"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "PricerInputOutOfRange",
    "inputs": [
      {
        "name": "which",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "SeriesUnknown",
    "inputs": [
      {
        "name": "seriesId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedDecimals",
    "inputs": [
      {
        "name": "decimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
